### ISSUE TITLE
error while build

### ISSUE THREAD

**Issue by petrparolek** [trainit/2018-03-nette-webpack#228]
```
vagrant@homestead:~/projects_local/playground/nette-webpack-example$  node -v
v14.15.3
vagrant@homestead:~/projects_local/playground/nette-webpack-example$
vagrant@homestead:~/projects_local/playground/nette-webpack-example$     npm run build

> 2018-03-nette-webpack@1.0.0 build /home/vagrant/projects_local/playground/nette-webpack-example
> cross-env NODE_ENV=production webpack --mode production --progress --colors

Invalid options object. Terser Plugin has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'chunkFilter'. These properties are valid:
   object { test?, include?, exclude?, cache?, cacheKeys?, parallel?, sourceMap?, minify?, terserOptions?, extractComments?, warningsFilter? }
ValidationError: Invalid options object. Terser Plugin has been initialized using an options object that does not match the API schema.
    at validate (/home/vagrant/projects_local/playground/nette-webpack-example/node_modules/terser-webpack-plugin/node_modules/schema-utils/dist/validate.js:96:11)
    at new TerserPlugin (/home/vagrant/projects_local/playground/nette-webpack-example/node_modules/terser-webpack-plugin/dist/index.js:40:30)
    at Object.<anonymous> (/home/vagrant/projects_local/playground/nette-webpack-example/webpack.config.js:313:5)
    at Module._compile (/home/vagrant/projects_local/playground/nette-webpack-example/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (/home/vagrant/projects_local/playground/nette-webpack-example/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! 2018-03-nette-webpack@1.0.0 build: `cross-env NODE_ENV=production webpack --mode production --progress --colors`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the 2018-03-nette-webpack@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2020-12-18T22_13_10_824Z-debug.log
```

**Comment by petrparolek** [comment]
Have you look at it @f3l1x ?

**Comment by f3l1x** [comment]
Fixed.
